### ISSUE TITLE
Expected data format?

### ISSUE THREAD

**Issue by mckinziebrandon** [microsoft/UniVL#1]
Hello, I was trying to run the README example(s) on the youcook2 dataset. I've downloaded all the files from the [youcook webpage](http://youcook2.eecs.umich.edu/download) and ran the download scripts. Reading through dataloader_youcook_caption.py seems to indicate you expect the data to be in some custom/different format. Is that correct? For example, I don't see any `.pickle` files in the original dataset, and none of the csv files have a column `feature_file`. Can you clarify the steps required to run the README?

**Comment by brunokinder** [comment]
Hi @mckinziebrandon ,

I have the same questions. It seems to me that the `csv` file has the format `video_id, feature_file` as for the training stages i and ii. I also think the format they expect for the captions is the same as in the training stages which means we would have to convert YouCook II format to this one. Did you have your answers?

Thanks.

**Comment by ArrowLuo** [comment]
@mckinziebrandon @brunokinder Hope the [readme](https://github.com/microsoft/UniVL/blob/main/dataloaders/README.md) in the dataloaders folder can answer your questions.

**Comment by brunokinder** [comment]
That is really great! Thanks a lot @ArrowLuo !
