### ISSUE TITLE
Captioning task clarification: video vs. video+text for captioning task

### ISSUE THREAD

**Issue by tchang1997** [microsoft/UniVL#16]
Just to clarify, is the MSR-VTT captioning pipeline the video-only task, or the video+transcript setting (as described in Sec. 4.3.2. of [your paper](https://arxiv.org/pdf/2002.06353.pdf))? Upon inspection, it seems like at test time, by default, the model simply takes in `[CLS] [SEP]` as the textual input -- so I'm led to believe that this is the video-only setting?

I am most interested in the video-only setting, so I just wanted to confirm. I'm currently trying to replicate your UniVL MSR-VTT captioning results to study some of the model capabilities and was able to get very similar metrics to those reported in the README.

Thank you so much for making your work easy to reproduce!

**Comment by ArrowLuo** [comment]
Hi @tchainzzz, sorry for the delayed reply. 

Yes, for the MSR-VTT, we only report on the video-only setting. For the UniVL, the video-only setting will take constant `[CLS] [SEP]` as text input.

**Comment by tchang1997** [comment]
Thanks so much for getting back so quickly -- that's exactly what I'm looking for!
