### ISSUE TITLE
How does the visual token come from?

### ISSUE THREAD

**Issue by renmada** [microsoft/UniVL#20]
As described in paper, S3D is used to extract video features and then feed features to Trasnformer.
But the source code in module_visual, using an Embedding.
My question is did you do some processing to convert video features to video tokens?

**Comment by ArrowLuo** [comment]
It may be a bad variable name. The Embedding in module_visual is Linear ([here](https://github.com/microsoft/UniVL/blob/main/modules/module_visual.py#L110)), so there is no token conversion.
