### ISSUE TITLE
What's mean of the 'step_size=5' in modeling.py

### ISSUE THREAD

**Issue by saicoco** [microsoft/UniVL#23]
does the 'step_size=5' mean that one video with five captions?

https://github.com/microsoft/UniVL/blob/main/modules/modeling.py#L346

**Comment by ArrowLuo** [comment]
Hi @saicoco, it is a trick to reduce the cost of GPU memory. The sequence_output is divided into many parts according to the `step_size=5`, then the `for loop` will process each part of them, finally, the similarity matrix will be gathered by `torch.cat()` (#L374).

**Comment by saicoco** [comment]
Got it
