### ISSUE TITLE
Pre-training acceleration using multi-machine distributed training

### ISSUE THREAD

**Issue by mingtan2** [microsoft/UniVL#29]
Hi @ArrowLuo ,

Thanks for the great work. I read in your paper that the second pre-training stage costs around 12 days using 8 GPUs. I am wondering if you tried to use multi-machine distributed training to accelerate it. Is your code base compatible with that? Thanks in advance.

**Comment by ArrowLuo** [comment]
Hi @mingtan2, Yes, you can run distributed training with `python -m torch.distributed.launch`. Good Luck!
