### ISSUE TITLE
end-to-end video file captioning process

### ISSUE THREAD

**Issue by mhyeonsoo** [microsoft/UniVL#36]
Hi, thanks for the great sources.
I successfully fine-tuned video captioning model for Youcook2, and now trying to input video file as a input and get the caption of it.
But when I see the code, it seems like it always require pickle file or npy feature file.
Is there a way to get the captioning script as an output with the custom video file input?
Thanks,

**Comment by ArrowLuo** [comment]
Hi @mhyeonsoo, I think you could modify the data loader as your requirement referring to [dataloader_youcook_caption.py](https://github.com/microsoft/UniVL/blob/main/dataloaders/dataloader_youcook_caption.py#L15). Best~

**Comment by mhyeonsoo** [comment]
Thanks, I will look into that :)

**Comment by cws7777** [comment]
Hi, @mhyeonsoo have you figured out this?
If you have, can you please share it?

Thanks!
