### ISSUE TITLE
CLip

### ISSUE THREAD

**Issue by johnbager** [microsoft/UniVL#4]
do you try to use CLIP to generate video-caption?
I think it will be useful.

**Comment by ArrowLuo** [comment]
@johnbager We have not done any tests on the video-caption-based CLIP. It is worth trying in this direction. The main problem is that the text encoder of CLIP encodes text with a [causal attention mask](https://github.com/openai/CLIP/blob/cfcffb90e69f37bf2ff1e988237a0fbe41f33c04/clip/model.py#L324). It leads that video feature (or images feature) may be insufficient for caption task. However, it is just my conjecture.
